// lib/titulosHero.ts
// Os 100 títulos rotativos do hero da home, copiados literalmente de
// docs/conteudo/titulos_hero_home.md — não reescrever nenhum aqui.

// Escolha determinística do título do dia: hash simples e estável de
// (data + usuário), sem client-side randomness e sem biblioteca. Mesmo
// usuário + mesmo dia => mesmo índice sempre (sem hydration mismatch,
// já que é resolvido no server component antes de renderizar).
export function tituloHeroDoDia(usuarioId: string, dataISO: string): string {
  const chave = `${dataISO}:${usuarioId}`
  let hash = 0
  for (let i = 0; i < chave.length; i++) {
    hash = (hash * 31 + chave.charCodeAt(i)) >>> 0
  }
  return TITULOS_HERO[hash % TITULOS_HERO.length]
}

export const TITULOS_HERO: string[] = [
  "Continue subindo.",
  "Bom te ver de novo.",
  "De volta ao jogo.",
  "Você voltou. Isso importa.",
  "Voltar já é vencer.",
  "Hoje conta.",
  "Faça o dia valer.",
  "Hoje constrói amanhã.",
  "Amanhã agradece o hoje.",
  "A elite estuda hoje.",
  "Bora pra aula.",
  "A prática te espera.",
  "Mostra a que veio.",
  "A constância vence.",
  "Sem pressa, sem pausa.",
  "É sobre não parar.",
  "Coragem é continuar.",
  "O hábito te carrega.",
  "Isso está virando hábito.",
  "Respira e continua.",
  "O jogo é longo.",
  "Quem estuda, assina laudo.",
  "O laudo começa aqui.",
  "Preparo gera nomeação.",
  "Um perito se faz assim.",
  "Perito se forja no estudo.",
  "Grandes peritos estudam.",
  "Ninguém nasce perito.",
  "Todo expert começou assim.",
  "Hoje treina, amanhã assina.",
  "Seu nome nos autos.",
  "O fórum nota quem domina.",
  "Quem domina, é chamado.",
  "Técnica vira reputação.",
  "De aluno a autoridade.",
  "Confiança se calcula.",
  "Seu futuro se calcula.",
  "Domine o processo.",
  "Sua planilha, sua arma.",
  "Você prova com números.",
  "Teoria hoje, laudo amanhã.",
  "Impossível de ignorar.",
  "Rumo à autoridade.",
  "Construa sua autoridade.",
  "Autoridade se conquista.",
  "Isso é alta performance.",
  "Excelência é repetição.",
  "Sua vaga na elite.",
  "O Selo te espera.",
  "Cada aula soma.",
  "De aula em aula.",
  "Sua trilha te espera.",
  "Siga o mapa.",
  "O mapa está na sua mão.",
  "Sua sequência importa.",
  "Você está mais perto.",
  "Você tem direção.",
  "Sua história em curso.",
  "Território em conquista.",
  "Um degrau por dia.",
  "Sobe que a vista melhora.",
  "Disciplina é liberdade.",
  "Aprender é o atalho.",
  "Sem atalho, com método.",
  "Método vence talento.",
  "Repetição cria mestres.",
  "O básico bem feito vence.",
  "O esforço aparece.",
  "Confiança vem da prática.",
  "A técnica se constrói assim.",
  "Estude como quem constrói.",
  "Passo firme, olhar longe.",
  "Progresso, não perfeição.",
  "A rotina dos campeões.",
  "Mais forte que ontem.",
  "O ritmo é seu.",
  "Isso te diferencia.",
  "Isso é compromisso.",
  "Você escolheu evoluir.",
  "Seu futuro em construção.",
  "Estude. O resto segue.",
  "Clareza convence.",
  "Precisão é assinatura.",
  "Rigor é respeito.",
  "Detalhe é diferencial.",
  "Simples é sofisticado.",
  "Prazo cumprido, nome feito.",
  "Entrega constrói confiança.",
  "Do estudo ao honorário.",
  "Pronto para o próximo caso.",
  "Faça por você.",
  "Você é o investimento.",
  "Aposta certa: você.",
  "Quem entende, explica.",
  "Reputação se estuda.",
  "Presença constrói futuro.",
  "Cada processo, uma chance.",
  "O contraditório não te assusta.",
  "Colhe quem estuda.",
  "Que dia bom pra evoluir.",
]
